-- Create result table if not exist
CREATE TABLE IF NOT EXISTS {association_table} cluster by (TRANSACTION_MONTH)  (
	PRIMARY_ID VARCHAR(1000),
	SECONDARY_ID VARCHAR(1000),
	PRIMARY_TRANSACTIONS NUMBER(18,0),
	SECONDARY_TRANSACTIONS NUMBER(18,0),
	PAIR_TRANSACTIONS NUMBER(18,0),
	TOTAL_TRANSACTIONS NUMBER(18,0),
	TRANSACTION_MONTH DATE,
	CUSTOMER_TYPE VARCHAR(100),
	COUNTRY_CODE VARCHAR(3),
	MODEL_TYPE VARCHAR(100),
	MODEL_NAME VARCHAR(100),
	WIN_SIZE  NUMBER(18,0),
	PROCESS_TS TIMESTAMP_NTZ(9) NOT NULL, 
	DW_AIRFLOW_DAG_RUN_ID VARCHAR(100) NOT NULL
);